#!/bin/bash
read -p "Which PI?: "  pinum

if [ -z $pinum ]; then
  for i in {01..20}
  do
       ping rpi$i -w 1 > /dev/null
       if [ $? -eq 0 ]; then
          echo "RPI$i is up"
       else 
          echo "RPI$i is down"
       fi
  done
else 
ping rpi$pinum -w 1 > /dev/null
if [ $? -eq 0 ]; then
          echo "RPI$pinum is up"
       else 
          echo "RPI$pinum is down"
fi
fi
echo "complete"
